title: Arnaud Ligny
baseline: 'Les liens'
baseurl: 'https://cecil.local/'
description: 'Quelques liens à propos de Arnaud Ligny.'
author:
  name: 'Arnaud Ligny'
  url: 'https://arnaudligny.fr'
image: avatar.jpeg
language: fr
languages:
  - code: fr
    locale: fr_FR
    name: Français
